source 'https://github.com/CocoaPods/Specs'

platform :ios, '9.0'

# Uncomment this line if you use Swift
# use_frameworks!

target 'Shuffle' do
  # Application Pods
  pod 'AFNetworking', '~> 3.1'
  pod 'Realm', '~> 1.1'
  # pod 'Realm+JSON', '~> 0.2'
  pod 'Realm+JSON', :git => 'https://github.com/matthewcheok/Realm-JSON', :commit => 'e5d69f0fb0d541cc2235a99c70a00b5bd0c0c59c'
end

abstract_target :unit_tests do
  target 'UnitTests'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
  pod 'OHHTTPStubs'
end


# Copy acknowledgements to the Settings.bundle

post_install do | installer |
  require 'fileutils'

  pods_acknowledgements_path = 'Pods/Target Support Files/Pods/Pods-Acknowledgements.plist'
  settings_bundle_path = Dir.glob("**/*Settings.bundle*").first

  if File.file?(pods_acknowledgements_path)
    puts 'Copying acknowledgements to Settings.bundle'
    FileUtils.cp_r(pods_acknowledgements_path, "#{settings_bundle_path}/Acknowledgements.plist", :remove_destination => true)
  end
end

